version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
    networks:
      - app-network
    restart: unless-stopped
    command: ["/wait-for-it.sh", "db:3306", "--timeout=120", "--", "uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "src"]

networks:
  app-network:

volumes:
  db-data: