version: "3.9"

services:
  api:
    image: woo204/winection-api:latest
    platform: linux/amd64
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - .env
      
  web:
    image: ggwakggwark2/winection-web:latest
    platform: linux/amd64
    container_name: web
    ports:
      - "3000:3000"