services:
  db:
    image: mysql:8.0
    container_name: winection-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network: