version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network: